services:
  - type: web
    name: catastro-tausa-web
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production

  - type: postgres
    name: catastro-tausa-db
    plan: free